# -*- coding: utf-8 -*-
"""
诊断危机干预模块的实际问题
"""

import sys
import io
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

print("=" * 70)
print("危机干预问题诊断".center(70))
print("=" * 70)

# 问题分析
print("\n【问题1】为什么执行了mindchat_system？")
print("-" * 70)
print("从日志看：")
print("  [危机检测] 用户 4: 检测到危机等级 3")
print("  [MindChat] 响应长度: 118 字符  ← 说明执行了mindchat！")
print()
print("代码逻辑：")
print("  flask_app.py:1290-1313")
print("    if intervention.should_cover:")
print("        response = intervention.content")
print("        return jsonify(...)  # ← 应该在这里return")
print()
print("  flask_app.py:1327")
print("    result = mindchat_system.analyze_and_respond(...)  # ← 但执行了这里")
print()
print("结论：代码没有在1290-1313之间return，继续执行了！")

print("\n【问题2】为什么没有return？")
print("-" * 70)
print("可能的原因：")
print("  1. intervention.should_cover = False")
print("     → 但Level 3应该返回True")
print()
print("  2. intervention.generate()时发生异常")
print("     → 异常被except捕获（1315-1318行）")
print("     → 然后继续执行")
print()
print("  3. intervention.content为空或None")
print("     → 保存数据库失败？")

print("\n【问题3】检查AI生成")
print("-" * 70)

# 模拟AI生成
print("检查responder是否使用AI生成：")
print("  flask_app.py:205")
print("    crisis_responder = CrisisResponder(")
print("        ai_generator=mindchat_system.generate_response")
print("    )")
print()
print("  config.py:34")
print("    USE_AI_GENERATION: bool = True  # ← 启用了AI生成")
print()
print("所以会调用：")
print("  content = mindchat_system.generate_response(prompt, user_context)")
print()
print("如果MindChat返回'抱歉，我遇到了一些问题'：")
print("  → intervention.content = 错误消息")
print("  → 保存到数据库")
print("  → return给前端")
print()
print("但为什么还会执行mindchat_system.analyze_and_respond？")

print("\n【问题4】检查实际日志")
print("-" * 70)
print("从用户提供的日志分析：")
print("  [危机检测] 用户 4: 检测到危机等级 3")
print("  [MindChat] 响应长度: 118 字符  ← 这是哪个MindChat？")
print()
print("可能的情况：")
print("  A. 危机干预中调用的MindChat")
print("     → responder._generate_by_ai()调用了mindchat_system")
print("     → 这个日志是干预生成的MindChat")
print()
print("  B. 正常对话的MindChat")
print("     → 危机检测return失败")
print("     → 继续执行到1327行")
print("     → 调用了正常的对话MindChat")
print()
print("需要检查日志中的'[MindChat]'是从哪里打印的")

print("\n【解决方案】")
print("-" * 70)
print("1. 添加更详细的日志来追踪执行流程")
print("2. 禁用AI生成，使用模板（更可靠）")
print("3. 修复return逻辑")
print()
print("临时方案：")
print("  修改config.py:")
print("    USE_AI_GENERATION: bool = False  # 禁用AI生成")
print()
print("这样responder会直接使用responses.json的模板，")
print("不会调用MindChat，更稳定可靠。")

print("\n" + "=" * 70)
print("诊断完成".center(70))
print("=" * 70)

print("\n建议：")
print("1. 添加更多日志来追踪问题")
print("2. 禁用AI生成（USE_AI_GENERATION=False）")
print("3. 验证return是否真的执行了")
